spring.application.name=cookies
server.port=8080

# JWT
jwt.secret=T4ll3rSpr1ngB00tJWT-S3cr3tK3y-C0mpl3t0-Ok!
jwt.expiration=3600000

# CORS - orígenes permitidos (Live Server de VS Code)
cors.allowed-origins=http://localhost:5500,http://127.0.0.1:5500,http://localhost:3000
